name: roistegapp
description: A Reversible Data Hiding Scheme In Encrypted Medical Imagess
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_steganography: ^0.0.2
  image_picker: any
  photo_view: any
  get: any
  image_cropper: ^1.4.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  encrypt: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ABeeZee
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf